// Code generated by Slice Machine. DO NOT EDIT.

import ContactForm from './ContactForm';
import EmbedSlice from './EmbedSlice';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	ContactForm,
	EmbedSlice,
	Image,
	Quote,
	Text,
};

export const components = {
	contact_form: ContactForm,
	embed_slice: EmbedSlice,
	image: Image,
	quote: Quote,
	text: Text,
};
